title: Letras & Versos
description: Un lugar para so√±ar y escribir
url: ""
baseurl: ""

markdown: kramdown

collections:
  poemas:
    output: true
  relatos:
    output: true
  reflexiones:
    output: true
